theme: jekyll-theme-giellalt
title: Dictionary for South Sámi ⇒ North Sámi
description: An electronic dictionary from South Sámi to North Sámi

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
